/** Page keys for view-only access (must match backend). */
export const APP_PAGES = [
  { key: "dashboard", label: "Dashboard" },
  { key: "clients", label: "Clients" },
  { key: "users", label: "Users" },
  { key: "user-view-access", label: "View access" },
  { key: "create-sites", label: "Create sites" },
  { key: "sitepack-management", label: "Sitepack management" },
  { key: "action-tracker", label: "Nonconformance" },
  { key: "general-forms", label: "Templates" },
  { key: "saved-signatures", label: "Saved signatures" },
  { key: "forms", label: "Form builder" },
  { key: "company", label: "Company" },
  { key: "report-health-safety", label: "Health & Safety concern" },
  { key: "report-environmental", label: "Sustainability concern" },
  { key: "report-quality", label: "Quality concern" },
  { key: "report-positive", label: "Positive observation" },
  { key: "concern-positive-report", label: "Concern & positive report" },
  { key: "weekly-supervisor", label: "Weekly supervisor inspection" },
  { key: "sheq", label: "SHEQ inspection" },
  { key: "shq-installation", label: "SHEQ installation" },
  { key: "lift-sector", label: "Lift sector analysis" },
  { key: "frida-forms", label: "Friday pack forms" },
];

export const PAGE_PATH_PREFIXES = [
  { key: "dashboard", paths: ["/dashboard", "/concern-reports", "/audit-reports", "/dashboard/occupational-health-safety-kpis", "/dashboard/environmental-management-kpis", "/dashboard/quality-management-kpis", "/dashboard/food-safety-management", "/dashboard/lift-regulations-management-kpis", "/monitoring/ohs", "/monitoring/environmental", "/monitoring/quality", "/monitoring/food-safety", "/monitoring/lift"] },
  { key: "clients", paths: ["/clients"] },
  { key: "users", paths: ["/users"] },
  { key: "user-view-access", paths: ["/user-view-access"] },
  { key: "view-invite", paths: ["/view-invite"], alwaysOn: true },
  { key: "create-sites", paths: ["/create-sites"] },
  { key: "sitepack-management", paths: ["/sitepack-management"] },
  { key: "action-tracker", paths: ["/nonconformance", "/action-tracker", "/nc", "/nc-calendar", "/nc-dashboard"] },
  { key: "general-forms", paths: ["/general-forms"] },
  { key: "saved-signatures", paths: ["/saved-signatures"] },
  { key: "forms", paths: ["/forms", "/form-build", "/create-form"] },
  { key: "company", paths: ["/company"] },
  { key: "report-health-safety", paths: ["/report-health-safety"] },
  { key: "report-environmental", paths: ["/report-environmental"] },
  { key: "report-quality", paths: ["/report-quality"] },
  { key: "report-positive", paths: ["/report-positive"] },
  { key: "concern-positive-report", paths: ["/concern-positive-report"] },
  { key: "weekly-supervisor", paths: ["/weekly-supervisor", "/weekly-reports"] },
  { key: "sheq", paths: ["/sheq-inspection", "/sheq-report", "/sheq-install-form"] },
  { key: "shq-installation", paths: ["/shq-installation"] },
  { key: "lift-sector", paths: ["/lift-sector-client", "/lift-sector-site"] },
  { key: "frida-forms", paths: ["/frida-forms"] },
  { key: "profile", paths: ["/profile"], alwaysOn: true },
  { key: "account-settings", paths: ["/account-settings"], alwaysOn: true },
];
